#!/usr/bin/env bash
#Display numbers 1 upto 100 and displays FizzBuzz

for count in {1..100}
do
	if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((count % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((count % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$count"
	fi
done
