#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=: read -r username x uid gid gecos home shell
do
  password=$(sudo grep "^$username:" /etc/shadow | cut -d: -f2)
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $uid"
done < /etc/passwd
