#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=: read -r username uid gid home shell
do
 # password=$(sudo grep "^$username:" /etc/shadow | cut -d: -f2)
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode $uid, more info about the user here: $username"
done < /etc/passwd
