#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
